Wahabk/issue132 transport prefix
NERSC/podman-hpc pull request #133
Opened 2024-12-17 16:31 UTC by wahabk

There isn't a `CONTRIB.md` so I have created a fork and PR.

Closes #132. TLDR: enables `podman-hpc pull docker://docker.io/library/ubuntu:latest`.

I thought that simply adding this after the `podman pull` subprocess would do the job instead of updating `MigrateUtils()`.

```python
def pull(ctx, siteconf, image, podman_args, **site_opts):
    """Pulls an image to a local repository and makes a squashed copy."""    
    cmd = [siteconf.podman_bin, "pull"]
    cmd.extend(podman_args)
    cmd.extend(siteconf.get_cmd_extensions("pull", site_opts))
    cmd.append(image)
    proc = Popen(cmd)
    proc.communicate()

    # Check for transport_prefix
    if "://" in image:
        transport_prefix, image = image.split("://", 1)
    else:
        transport_prefix = None
```

- [ ] Do you reckon this is a good place for the check? Or should it be after `if proc.returncode == 0:`?
- [ ] Can you think of another Podman-HPC wrapped function that would be affected by transport prefixes?
- [ ] I don't currently have a dev environment for `podman-hpc`. If you would accept this change / or have feedback do let me know and I'll do some testing.

2025-01-03 15:43 UTC, wahabk commented
I note that the format is `oci-archive:path:tag` and not the separator `://`. More examples available here https://docs.podman.io/en/latest/markdown/podman-pull.1.html#source

2025-01-03 20:23 UTC, scanon requested changes
See my suggestions

2025-01-03 20:23 UTC, scanon commented on podman_hpc/podman_hpc.py
> +    """Pulls an image to a local repository and makes a squashed copy."""
Can you fix the trailing whitespaces?

2025-01-03 20:23 UTC, scanon commented on podman_hpc/podman_hpc.py
> +        transport_prefix, image = image.split("://", 1)
Since the prefix isn't used, maybe replace this with just
```
if "://" in image:
        image = image.split("://", 1)[0]
```

2025-01-03 20:23 UTC, scanon commented on podman_hpc/podman_hpc.py
> +    else:
You can drop the else section since we don't use the transport prefix

2025-01-03 20:23 UTC, scanon commented
Thanks for the report and proposed fix.  This looks good and this seems a reasonable place to handle it.  Can you do a few minor things just to keep the flake8 happy.

I'll add a few other minor comments and then we can merge it.

2025-02-03 15:59 UTC, wahabk commented on podman_hpc/podman_hpc.py
> +    """Pulls an image to a local repository and makes a squashed copy."""
Done

2025-02-03 15:59 UTC, wahabk commented on podman_hpc/podman_hpc.py
> +    else:
done

2025-02-03 16:00 UTC, wahabk commented on podman_hpc/podman_hpc.py
> +        transport_prefix, image = image.split("://", 1)
I have updated this to check for the entire prefix

```
PODMAN_TRANSPORT_PREFIXES = [
    "docker://",
    "dir:",
    "docker-archive:",
    "docker-daemon:",
    "oci-archive:",
]

# podman-hpc pull subcommand (modified) ####################################
@podhpc.command(
    context_settings=dict(
        ignore_unknown_options=True,
    ),
    options_metavar="[options]",
)
@pass_siteconf
@click.pass_context
@click.argument("podman_args", nargs=-1, type=click.UNPROCESSED)
@click.argument("image")
def pull(ctx, siteconf, image, podman_args, **site_opts):
    """Pulls an image to a local repository and makes a squashed copy."""
    cmd = [siteconf.podman_bin, "pull"]
    cmd.extend(podman_args)
    cmd.extend(siteconf.get_cmd_extensions("pull", site_opts))
    cmd.append(image)
    proc = Popen(cmd)
    proc.communicate()

    # Check for transport_prefix
    for prefix in PODMAN_TRANSPORT_PREFIXES:
        if image.startswith(prefix):
            if prefix != "docker://":
                sys.stderr.write(
                    f"""WARNING: Transport prefix '{prefix}' is
                                 incompatible with podman-hpc.\n"""
                )
            image = image[len(prefix) :]  # Remove the prefix
            break
```

2025-02-03 16:05 UTC, wahabk commented
Thanks for your feedback @scanon! I have included it in this commit. I tried running `black --line-length 79 .` but this updates many files in the repo.

I have updated this PR to check for the entire prefix

```python
PODMAN_TRANSPORT_PREFIXES = [
    "docker://",
    "dir:",
    "docker-archive:",
    "docker-daemon:",
    "oci-archive:",
]

# podman-hpc pull subcommand (modified) ####################################
@podhpc.command(
    context_settings=dict(
        ignore_unknown_options=True,
    ),
    options_metavar="[options]",
)
@pass_siteconf
@click.pass_context
@click.argument("podman_args", nargs=-1, type=click.UNPROCESSED)
@click.argument("image")
def pull(ctx, siteconf, image, podman_args, **site_opts):
    """Pulls an image to a local repository and makes a squashed copy."""
    cmd = [siteconf.podman_bin, "pull"]
    cmd.extend(podman_args)
    cmd.extend(siteconf.get_cmd_extensions("pull", site_opts))
    cmd.append(image)
    proc = Popen(cmd)
    proc.communicate()

    # Check for transport_prefix
    for prefix in PODMAN_TRANSPORT_PREFIXES:
        if image.startswith(prefix):
            if prefix != "docker://":
                sys.stderr.write(
                    f"""WARNING: Transport prefix '{prefix}' is
                                 incompatible with podman-hpc.\n"""
                )
            image = image[len(prefix) :]  # Remove the prefix
            break
```

This would only work with the `"docker://"` prefix, the others would require additional functionality. Therefore, I have raised a warning. What are your thoughts?

2025-02-10 13:23 UTC, wahabk commented
For my reference, this is the OCI image specification for transport prefixes:



https://github.com/containers/image/blob/main/docs/containers-transports.5.md#dockerdocker-reference

2025-03-25 14:08 UTC, wahabk commented
Closing as it is difficult to support all prefixes.

2025-03-25 14:08 UTC, closed without merging