Add auto shared-run support
NERSC/podman-hpc pull request #22
Opened 2023-01-25 18:57 UTC by scanon

This adds a new module option to enable shared-run.  So even if the user just use `run` it will switch to shared-run

2023-01-30 18:56 UTC, lastephey requested changes

2023-01-30 18:56 UTC, lastephey commented on podman_hpc/siteconfig.py
> +    mount_program = "fuse-overlayfs-warp"
I think this is a typo and should be `fuse-overlayfs-wrap` based on what I see in `/usr/bin`

2023-01-31 00:24 UTC, lastephey commented on podman_hpc/siteconfig.py
> +    mount_program = "fuse-overlayfs-warp"
Nevermind I see this was fixed in a later commit

2023-01-31 00:24 UTC, lastephey approved these changes

2023-02-02 02:37 UTC, danfulton approved these changes
This all LGTM.

2023-02-02 17:40 UTC, merged