WIP: start adding nccl ss11 module
NERSC/podman-hpc pull request #32
Opened 2023-02-14 22:23 UTC by lastephey

Adds a podman-hpc version of the current shifter NCCL ss11 module

WIP since it still needs to be fully tested on muller

2023-03-15 23:44 UTC, lastephey commented
Ok should be ready for review @danfulton and @scanon. To work correctly requires https://github.com/NERSC/podman-hpc/pull/41

Should now match what is in https://gitlab.nersc.gov/nersc/csg/nersc-cle/-/merge_requests/3885

2023-03-17 00:04 UTC, danfulton commented
Otherwise, LGTM.

2023-03-17 00:05 UTC, danfulton requested changes

2023-03-17 00:05 UTC, danfulton commented on etc/modules.d/nccl.yaml
Should we remove the `bind:` or make it `bind: []`?  I know the `hook_tool` will handle it, but not sure if it's technically valid yaml.

2023-03-17 00:05 UTC, danfulton commented on etc/modules.d/nccl.yaml
No strong opinion, I think python just parses it as `{"bind": None}`

2023-03-17 17:02 UTC, lastephey commented on etc/modules.d/nccl.yaml
Looks like it's optional, so I'll just remove.

2023-03-17 17:36 UTC, danfulton commented on etc/modules.d/nccl.yaml
I confirm the latest `hook_tool` PR works with both absent and `None` sections... that was a bug I encountered and fixed.  :)

2023-03-17 17:36 UTC, danfulton commented
LGTM

2023-03-17 17:37 UTC, danfulton commented
Oops, I meant to close my review not the PR... sorry.

2023-03-17 17:38 UTC, danfulton approved these changes

2023-03-17 23:10 UTC, merged